name: Daily Commit

on:
  schedule:
    - cron: '0 */4 * * *'  # Setiap 4 jam sekali (UTC)
  workflow_dispatch:

jobs:
  update-and-commit:
    runs-on: ubuntu-latest

    env:
      ULTRA_MSG_INSTANCE_ID: ${{ secrets.ULTRA_MSG_INSTANCE_ID }}
      ULTRA_MSG_TOKEN: ${{ secrets.ULTRA_MSG_TOKEN }}
      WHATSAPP_NUMBER: ${{ secrets.WHATSAPP_NUMBER }}
      _TOKEN: ${{ secrets._TOKEN }}
      _OWNER: ${{ secrets._OWNER }}
      _REPO: ${{ secrets._REPO }}
      _BASE_BRANCH: ${{ secrets._BASE_BRANCH }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run update script
      run: node bot.js
