name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'     # UTC 00:00 = 07:00 WIB
    - cron: '0 4 * * *'     # UTC 04:00 = 11:00 WIB
    - cron: '0 10 * * *'    # UTC 10:00 = 17:00 WIB
  workflow_dispatch: # bisa dijalankan manual juga

jobs:
  update-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run update script
      run: node bot.js

    - name: Commit changes
      run: |
        git config user.name "sayyidazizii"
        git config user.email "sayyidsyafiq234@gmail.com"
        git add .
        git commit -m "Daily update" || echo "No changes to commit"

    - name: Push changes
      uses: ad-m/github-push-action@v0.8.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
